.phony all:
all: diskinfo disklist diskget diskput

diskinfo: diskinfo.c
	gcc diskinfo.c -Wall -o diskinfo

disklist: disklist.c
	gcc disklist.c -Wall -o disklist

diskget: diskget.c
	gcc diskget.c -Wall -o diskget

diskput: diskput.c
	gcc diskput.c -Wall -o diskput
.PHONY clean:
clean:
	-rm -rf *.o *.exe


